import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    position: 'relative',
  },
  backgroundGlow: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 256,
    height: 256,
    backgroundColor: 'rgba(198, 244, 50, 0.05)',
    borderRadius: 128,
  },
  flex1: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  header: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    alignSelf: 'flex-start',
    backgroundColor: Colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  editOverviewContainer: {
    gap: 16,
  },
  editNameInput: {
    width: '100%',
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.onSurface,
  },
  editDescInput: {
    width: '100%',
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: Colors.onSurface,
    textAlignVertical: 'top',
  },
  editActionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 8,
  },
  cancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
  },
  cancelText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: Colors.electric,
    borderRadius: 8,
  },
  saveText: {
    color: Colors.black,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  overviewContainer: {
    gap: 12,
  },
  splitStudioTag: {
    backgroundColor: 'rgba(198, 244, 50, 0.15)',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
    marginBottom: 8,
  },
  splitStudioText: {
    fontSize: 10,
    color: Colors.electric,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  workoutName: {
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: 1,
    color: Colors.onSurface,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  workoutDesc: {
    color: Colors.mutedGray,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 18,
  },
  headerActionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  completeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.electric,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  opacity50: {
    opacity: 0.5,
  },
  completeText: {
    color: Colors.black,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginLeft: 6,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  editText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginLeft: 6,
  },
  tabsContainer: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  tabsContent: {
    paddingHorizontal: 20,
  },
  tabButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    marginRight: 8,
  },
  tabButtonActive: {
    borderBottomColor: Colors.electric,
  },
  tabText: {
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginLeft: 8,
  },
  tabTextActive: {
    color: Colors.electric,
  },
  tabTextInactive: {
    color: Colors.mutedGray,
  },
  tabPane: {
    padding: 20,
  },
  paneContent: {
    gap: 24,
  },
  paneHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  paneTitle: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 1,
    color: Colors.onSurface,
    textTransform: 'uppercase',
  },
  addExButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.electric,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  addExText: {
    color: Colors.black,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginLeft: 6,
  },
  addSchedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  addSchedText: {
    color: Colors.white,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginLeft: 6,
  },
  paneContentSpacing: {
    gap: 24,
  },
  cardContainer: {
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
    overflow: 'hidden',
  },
  exItem: {
    padding: 16,
  },
  borderBottom: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  exItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  exItemTitleBox: {
    flex: 1,
    paddingRight: 16,
  },
  exItemName: {
    fontWeight: 'bold',
    color: Colors.onSurface,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  exItemMuscles: {
    fontSize: 9,
    color: Colors.mutedGray,
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
  exItemActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionBtn: {
    padding: 6,
    backgroundColor: Colors.surface,
    borderRadius: 4,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  statBox: {
    backgroundColor: Colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    flex: 1,
    alignItems: 'center',
  },
  statBoxElectric: {
    backgroundColor: 'rgba(198, 244, 50, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(198, 244, 50, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    flex: 1,
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 10,
    color: Colors.mutedGray,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  statVal: {
    fontSize: 14,
    fontWeight: '900',
    color: Colors.white,
  },
  statLabelElectric: {
    fontSize: 10,
    color: Colors.electric,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  statValElectric: {
    fontSize: 14,
    fontWeight: '900',
    color: Colors.electric,
  },
  statUnit: {
    fontSize: 9,
  },
  setsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  setCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  setCircleActive: {
    backgroundColor: Colors.electric,
    borderColor: Colors.electric,
  },
  setCircleInactive: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
  },
  setCircleText: {
    fontSize: 10,
    fontWeight: '900',
  },
  setCircleTextActive: {
    color: Colors.black,
  },
  setCircleTextInactive: {
    color: Colors.mutedGray,
  },
  studioCard: {
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
    padding: 20,
  },
  studioTitle: {
    fontWeight: 'bold',
    color: Colors.onSurface,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontSize: 12,
    marginBottom: 4,
  },
  studioSubtitle: {
    color: Colors.mutedGray,
    fontSize: 9,
    textTransform: 'uppercase',
    fontWeight: 'bold',
    marginBottom: 16,
  },
  mapContainer: {
    backgroundColor: 'rgba(13, 13, 15, 0.4)',
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  targetsContainer: {
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: 12,
  },
  targetsTitle: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    color: Colors.onSurface,
    letterSpacing: 2,
    marginBottom: 8,
  },
  noMusclesText: {
    fontSize: 10,
    color: Colors.mutedGray,
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
  targetsList: {
    gap: 12,
  },
  primaryTitle: {
    fontSize: 8,
    fontWeight: '900',
    color: Colors.electric,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: 4,
  },
  secondaryTitle: {
    fontSize: 8,
    fontWeight: '900',
    color: Colors.electricOrange,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: 4,
  },
  marginTop8: {
    marginTop: 8,
  },
  tagWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  primaryTag: {
    backgroundColor: 'rgba(198, 244, 50, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(198, 244, 50, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  primaryTagText: {
    fontSize: 9,
    fontWeight: '900',
    color: Colors.electric,
    textTransform: 'uppercase',
  },
  secondaryTag: {
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 53, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  secondaryTagText: {
    fontSize: 9,
    fontWeight: '900',
    color: Colors.electricOrange,
    textTransform: 'uppercase',
  },
  cardContainerComment: {
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
    padding: 16,
  },
  commentInputTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: Colors.mutedGray,
    marginBottom: 8,
  },
  commentInputBox: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: Colors.onSurface,
    marginBottom: 12,
    textAlignVertical: 'top',
  },
  postButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingVertical: 8,
  },
  postButtonActive: {
    backgroundColor: Colors.electric,
  },
  postButtonDisabled: {
    backgroundColor: Colors.surface,
    opacity: 0.5,
  },
  postButtonText: {
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginLeft: 6,
  },
  textWhite: {
    color: Colors.white,
  },
  textBlack: {
    color: Colors.black,
  },
  commentItem: {
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    gap: 12,
  },
  avatarBox: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  commentAuthor: {
    fontWeight: 'bold',
    color: Colors.onSurface,
    textTransform: 'uppercase',
    fontSize: 12,
  },
  commentDate: {
    fontSize: 9,
    color: Colors.mutedGray,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  commentActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionBtnMargin: {
    padding: 4,
  },
  commentText: {
    fontSize: 14,
    color: Colors.onSurface,
    marginTop: 4,
  },
  editCommentWrap: {
    marginTop: 8,
  },
  editCommentInput: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: Colors.onSurface,
    marginBottom: 8,
  },
  editCommentActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  cancelCommentBtn: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 4,
  },
  cancelCommentText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: Colors.white,
    textTransform: 'uppercase',
  },
  saveCommentBtn: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: Colors.electric,
    borderRadius: 4,
  },
  saveCommentText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: Colors.black,
    textTransform: 'uppercase',
  },
  noCommentsText: {
    textAlign: 'center',
    color: Colors.mutedGray,
    fontSize: 12,
    textTransform: 'uppercase',
    fontWeight: 'bold',
    marginTop: 16,
  },
  schedItem: {
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  schedItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  schedIconBox: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  schedIconBoxPending: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  schedIconBoxCompleted: {
    backgroundColor: 'rgba(198, 244, 50, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(198, 244, 50, 0.2)',
  },
  schedDateText: {
    fontWeight: 'bold',
    color: Colors.onSurface,
    textTransform: 'uppercase',
    fontSize: 14,
  },
  schedTimeText: {
    fontSize: 10,
    color: Colors.mutedGray,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  schedActions: {
    flexDirection: 'row',
    gap: 8,
  },
  timerFloat: {
    position: 'absolute',
    bottom: 24,
    alignSelf: 'center',
    backgroundColor: '#1A1A1F',
    borderWidth: 1,
    borderColor: 'rgba(198, 244, 50, 0.3)',
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    elevation: 5,
    shadowColor: Colors.electric,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    zIndex: 50,
  },
  timerText: {
    color: Colors.white,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 2,
    width: 48,
    textAlign: 'center',
  },
  timerClose: {
    padding: 4,
  },
  modalContent: {
    gap: 16,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: Colors.mutedGray,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  modalInputWrap: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    overflow: 'hidden',
  },
  fakePickerRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  fakePickerText: {
    color: Colors.white,
    fontSize: 14,
  },
  modalTextInput: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    color: Colors.white,
  },
  modalTextInputBox: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: Colors.white,
    fontWeight: 'bold',
  },
  rowGap4: {
    flexDirection: 'row',
    gap: 16,
  },
  modalSaveBtn: {
    backgroundColor: Colors.electric,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  modalSaveText: {
    color: Colors.black,
    fontWeight: '900',
    textTransform: 'uppercase',
    fontSize: 14,
    letterSpacing: 1,
  },
});
